/**This is de the main form from the app where user can use the app.
 *
 * @author Orlando X. Perez Varela
 */
public class App_main extends javax.swing.JFrame {

    /**
     * Creates new form app_main
     */
    public App_main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator9 = new javax.swing.JSeparator();
        jSeparator10 = new javax.swing.JSeparator();
        backgroundPNL = new javax.swing.JPanel();
        titleLBL = new javax.swing.JLabel();
        changerInputFields = new javax.swing.JTabbedPane();
        userInfoPNL = new javax.swing.JPanel();
        firstnameLBL = new javax.swing.JLabel();
        lastnameLBL = new javax.swing.JLabel();
        middlenameLBL = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        subSectTittleLBL = new javax.swing.JLabel();
        firstnameInputTXTF = new javax.swing.JTextField();
        midnameInputTXTF = new javax.swing.JTextField();
        lastnameInputTXTF = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        subSectTittleLBL1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        firstnameLBL1 = new javax.swing.JLabel();
        middlenameLBL1 = new javax.swing.JLabel();
        lastnameLBL1 = new javax.swing.JLabel();
        firstnameOutputTXTF = new javax.swing.JTextField();
        midnameOutputTXTF = new javax.swing.JTextField();
        lastnameOutputTXTF = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        showInfoBTTN = new javax.swing.JButton();
        clearBTTN = new javax.swing.JButton();
        closeBTTN = new javax.swing.JButton();
        userMssgPNL = new javax.swing.JPanel();
        subSectTitleLBL3 = new javax.swing.JLabel();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        userMssgOutput = new javax.swing.JTextArea();
        subSectTitleLBL4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        userMssgTxtBx = new javax.swing.JTextArea();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        showMssgBTTN = new javax.swing.JButton();
        clearMssgBTTN = new javax.swing.JButton();
        closeBTTN1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Hash Code Generator");
        setLocationByPlatform(true);

        backgroundPNL.setBackground(new java.awt.Color(0, 0, 0));

        titleLBL.setBackground(new java.awt.Color(0, 102, 255));
        titleLBL.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        titleLBL.setForeground(new java.awt.Color(0, 102, 255));
        titleLBL.setText("Welcome User! If you want to know how your name or a message looks Encripted  please fill up the the following blanks.");

        changerInputFields.setBackground(new java.awt.Color(0, 102, 255));
        changerInputFields.setBorder(javax.swing.BorderFactory.createCompoundBorder(null, javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0))));

        userInfoPNL.setBackground(new java.awt.Color(0, 102, 255));
        userInfoPNL.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));

        firstnameLBL.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        firstnameLBL.setText("First Name:");

        lastnameLBL.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lastnameLBL.setText("Last Name:");

        middlenameLBL.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        middlenameLBL.setText("Middle Name:");

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        subSectTittleLBL.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        subSectTittleLBL.setText("Your Input");
        subSectTittleLBL.setAlignmentX(0.5F);

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        subSectTittleLBL1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        subSectTittleLBL1.setText("Your Result");
        subSectTittleLBL1.setAlignmentX(0.5F);

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator5.setOrientation(javax.swing.SwingConstants.VERTICAL);

        firstnameLBL1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        firstnameLBL1.setText("First Name:");

        middlenameLBL1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        middlenameLBL1.setText("Middle Name:");

        lastnameLBL1.setFont(new java.awt.Font("Segoe UI Semibold", 1, 14)); // NOI18N
        lastnameLBL1.setText("Last Name:");

        firstnameOutputTXTF.setEditable(false);

        midnameOutputTXTF.setEditable(false);

        lastnameOutputTXTF.setEditable(false);

        jSeparator6.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator6.setOrientation(javax.swing.SwingConstants.VERTICAL);

        showInfoBTTN.setBackground(new java.awt.Color(0, 255, 0));
        showInfoBTTN.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        showInfoBTTN.setText("Show Encription");
        showInfoBTTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showInfoBTTNMouseClicked(evt);
            }
        });

        clearBTTN.setBackground(new java.awt.Color(255, 255, 0));
        clearBTTN.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        clearBTTN.setText("Clear Input");
        clearBTTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearBTTNMouseClicked(evt);
            }
        });

        closeBTTN.setBackground(new java.awt.Color(255, 0, 0));
        closeBTTN.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        closeBTTN.setText("Close App");
        closeBTTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBTTNMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout userInfoPNLLayout = new javax.swing.GroupLayout(userInfoPNL);
        userInfoPNL.setLayout(userInfoPNLLayout);
        userInfoPNLLayout.setHorizontalGroup(
            userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userInfoPNLLayout.createSequentialGroup()
                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(userInfoPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(userInfoPNLLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(subSectTittleLBL)
                                .addGap(124, 124, 124)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(userInfoPNLLayout.createSequentialGroup()
                                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(middlenameLBL)
                                    .addComponent(firstnameLBL)
                                    .addComponent(lastnameLBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(firstnameInputTXTF)
                                    .addComponent(midnameInputTXTF)
                                    .addComponent(lastnameInputTXTF))
                                .addGap(14, 14, 14)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userInfoPNLLayout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addComponent(subSectTittleLBL1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 131, Short.MAX_VALUE)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userInfoPNLLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator4)
                            .addGroup(userInfoPNLLayout.createSequentialGroup()
                                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstnameLBL1)
                                    .addComponent(middlenameLBL1)
                                    .addComponent(lastnameLBL1))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lastnameOutputTXTF)
                                    .addComponent(firstnameOutputTXTF)
                                    .addComponent(midnameOutputTXTF))))))
                .addGap(18, 18, 18)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(showInfoBTTN, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(clearBTTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(closeBTTN, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        userInfoPNLLayout.setVerticalGroup(
            userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator6)
            .addGroup(userInfoPNLLayout.createSequentialGroup()
                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userInfoPNLLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userInfoPNLLayout.createSequentialGroup()
                                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(subSectTittleLBL))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstnameLBL)
                                    .addComponent(firstnameInputTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(middlenameLBL)
                                    .addComponent(midnameInputTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lastnameLBL)
                                    .addComponent(lastnameInputTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 58, Short.MAX_VALUE))
                            .addComponent(jSeparator3)))
                    .addGroup(userInfoPNLLayout.createSequentialGroup()
                        .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(userInfoPNLLayout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subSectTittleLBL1)
                                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(firstnameLBL1)
                                    .addComponent(firstnameOutputTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(middlenameLBL1)
                                    .addComponent(midnameOutputTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(userInfoPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lastnameLBL1)
                                    .addComponent(lastnameOutputTXTF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(userInfoPNLLayout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(showInfoBTTN)
                                .addGap(18, 18, 18)
                                .addComponent(clearBTTN)
                                .addGap(18, 18, 18)
                                .addComponent(closeBTTN)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        changerInputFields.addTab("Your Name", userInfoPNL);

        userMssgPNL.setBackground(new java.awt.Color(0, 102, 255));

        subSectTitleLBL3.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        subSectTitleLBL3.setText("Your Input");

        jSeparator7.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator7.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator8.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator11.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator11.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 14)); // NOI18N
        jLabel1.setText("Message");

        userMssgOutput.setEditable(false);
        userMssgOutput.setColumns(20);
        userMssgOutput.setRows(5);
        jScrollPane1.setViewportView(userMssgOutput);

        subSectTitleLBL4.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        subSectTitleLBL4.setText("Your Result");

        userMssgTxtBx.setColumns(20);
        userMssgTxtBx.setRows(5);
        jScrollPane2.setViewportView(userMssgTxtBx);

        jSeparator12.setForeground(new java.awt.Color(0, 0, 0));

        jSeparator13.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator13.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jSeparator14.setForeground(new java.awt.Color(0, 0, 0));
        jSeparator14.setOrientation(javax.swing.SwingConstants.VERTICAL);

        showMssgBTTN.setBackground(new java.awt.Color(0, 255, 0));
        showMssgBTTN.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        showMssgBTTN.setText("Show Encripted Message");
        showMssgBTTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                showMssgBTTNMouseClicked(evt);
            }
        });

        clearMssgBTTN.setBackground(new java.awt.Color(255, 255, 0));
        clearMssgBTTN.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        clearMssgBTTN.setText("Clear Input");
        clearMssgBTTN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearMssgBTTNMouseClicked(evt);
            }
        });

        closeBTTN1.setBackground(new java.awt.Color(255, 0, 0));
        closeBTTN1.setFont(new java.awt.Font("Segoe UI Black", 0, 18)); // NOI18N
        closeBTTN1.setText("Close App");
        closeBTTN1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closeBTTN1MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout userMssgPNLLayout = new javax.swing.GroupLayout(userMssgPNL);
        userMssgPNL.setLayout(userMssgPNLLayout);
        userMssgPNLLayout.setHorizontalGroup(
            userMssgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMssgPNLLayout.createSequentialGroup()
                .addGroup(userMssgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userMssgPNLLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(subSectTitleLBL3)
                        .addGap(102, 102, 102)
                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(userMssgPNLLayout.createSequentialGroup()
                        .addGroup(userMssgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(userMssgPNLLayout.createSequentialGroup()
                                .addGap(138, 138, 138)
                                .addComponent(jLabel1)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator7, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(userMssgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(jSeparator12)
                    .addGroup(userMssgPNLLayout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addComponent(subSectTitleLBL4)
                        .addGap(75, 75, 75)
                        .addComponent(jSeparator13)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator14, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(userMssgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showMssgBTTN, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(clearMssgBTTN, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(closeBTTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(16, Short.MAX_VALUE))
            .addGroup(userMssgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(userMssgPNLLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jScrollPane2)
                    .addGap(671, 671, 671)))
        );
        userMssgPNLLayout.setVerticalGroup(
            userMssgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userMssgPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userMssgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(userMssgPNLLayout.createSequentialGroup()
                        .addGroup(userMssgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator7)
                            .addGroup(userMssgPNLLayout.createSequentialGroup()
                                .addGroup(userMssgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(userMssgPNLLayout.createSequentialGroup()
                                        .addComponent(jSeparator11, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMssgPNLLayout.createSequentialGroup()
                                        .addComponent(subSectTitleLBL3)
                                        .addGap(18, 18, 18)))
                                .addComponent(jSeparator8, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel1)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(userMssgPNLLayout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addGroup(userMssgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(subSectTitleLBL4)
                            .addComponent(jSeparator13, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator12, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 111, Short.MAX_VALUE)
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, userMssgPNLLayout.createSequentialGroup()
                        .addComponent(jSeparator14)
                        .addContainerGap())))
            .addGroup(userMssgPNLLayout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addComponent(showMssgBTTN)
                .addGap(18, 18, 18)
                .addComponent(clearMssgBTTN)
                .addGap(18, 18, 18)
                .addComponent(closeBTTN1)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(userMssgPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(userMssgPNLLayout.createSequentialGroup()
                    .addGap(107, 107, 107)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                    .addGap(16, 16, 16)))
        );

        changerInputFields.addTab("Your Message", userMssgPNL);

        javax.swing.GroupLayout backgroundPNLLayout = new javax.swing.GroupLayout(backgroundPNL);
        backgroundPNL.setLayout(backgroundPNLLayout);
        backgroundPNLLayout.setHorizontalGroup(
            backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleLBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(changerInputFields))
                .addContainerGap())
        );
        backgroundPNLLayout.setVerticalGroup(
            backgroundPNLLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundPNLLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(titleLBL, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(changerInputFields)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backgroundPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backgroundPNL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //Event that is activate when use click closeBTTN.
    private void closeBTTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBTTNMouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBTTNMouseClicked

    //Event that is activate when use click clearBTTN.
    private void clearBTTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearBTTNMouseClicked
        //Clearing the fieds.
        firstnameInputTXTF.setText(null);
        midnameInputTXTF.setText(null);
        lastnameInputTXTF.setText(null);
        firstnameOutputTXTF.setText(null);
        midnameOutputTXTF.setText(null);
        lastnameOutputTXTF.setText(null);
    }//GEN-LAST:event_clearBTTNMouseClicked

    //Event that is activate when use click showInfoBTTN.
    private void showInfoBTTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showInfoBTTNMouseClicked
        //Declaration of local variables and pointer.
        String firstnameToSend,
        midnameToSend,
        lastnameToSend;
        Hashing sendInfo;

        //Getting up values entered by the user.
        firstnameToSend = firstnameInputTXTF.getText();
        midnameToSend = midnameInputTXTF.getText();
        lastnameToSend = lastnameInputTXTF.getText();

        //Setting up a value to the pointer.
        sendInfo = new Hashing(firstnameToSend, midnameToSend, lastnameToSend);

        //Setting up values to the textflieds.
        firstnameOutputTXTF.setText(sendInfo.getFirstname());
        midnameOutputTXTF.setText(sendInfo.getMidname());
        lastnameOutputTXTF.setText(sendInfo.getLastname());
    }//GEN-LAST:event_showInfoBTTNMouseClicked

    //Event that is activate when use click showMssgBTTN
    private void showMssgBTTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_showMssgBTTNMouseClicked
         //Declaration of local variables and pointer.
        String mssgToSend;
        Hashing sendMssg;
        
        //Getting up value entered by the user.
        mssgToSend = userMssgTxtBx.getText();
        
        //Setting up a value to the pointer.
        sendMssg = new Hashing(mssgToSend);
        
         //Setting up values to the textarea.
        userMssgOutput.setText(sendMssg.getMessage());
    }//GEN-LAST:event_showMssgBTTNMouseClicked

    //Event that is activate when use click clearBTTN.
    private void clearMssgBTTNMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearMssgBTTNMouseClicked
        // Clearing the textArea
        userMssgTxtBx.setText(null);
        userMssgOutput.setText(null);
    }//GEN-LAST:event_clearMssgBTTNMouseClicked

    //Event that is activate when use click closeBTTN.
    private void closeBTTN1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closeBTTN1MouseClicked
        System.exit(0);
    }//GEN-LAST:event_closeBTTN1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(App_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(App_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(App_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(App_main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new App_main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPNL;
    private javax.swing.JTabbedPane changerInputFields;
    private javax.swing.JButton clearBTTN;
    private javax.swing.JButton clearMssgBTTN;
    private javax.swing.JButton closeBTTN;
    private javax.swing.JButton closeBTTN1;
    private javax.swing.JTextField firstnameInputTXTF;
    private javax.swing.JLabel firstnameLBL;
    private javax.swing.JLabel firstnameLBL1;
    private javax.swing.JTextField firstnameOutputTXTF;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTextField lastnameInputTXTF;
    private javax.swing.JLabel lastnameLBL;
    private javax.swing.JLabel lastnameLBL1;
    private javax.swing.JTextField lastnameOutputTXTF;
    private javax.swing.JLabel middlenameLBL;
    private javax.swing.JLabel middlenameLBL1;
    private javax.swing.JTextField midnameInputTXTF;
    private javax.swing.JTextField midnameOutputTXTF;
    private javax.swing.JButton showInfoBTTN;
    private javax.swing.JButton showMssgBTTN;
    private javax.swing.JLabel subSectTitleLBL3;
    private javax.swing.JLabel subSectTitleLBL4;
    private javax.swing.JLabel subSectTittleLBL;
    private javax.swing.JLabel subSectTittleLBL1;
    private javax.swing.JLabel titleLBL;
    private javax.swing.JPanel userInfoPNL;
    private javax.swing.JTextArea userMssgOutput;
    private javax.swing.JPanel userMssgPNL;
    private javax.swing.JTextArea userMssgTxtBx;
    // End of variables declaration//GEN-END:variables
}
